version: 2.1

jobs:
  node-test:
    docker:
      - image: node:4.4.6
    resource_class: 'medium+'
    steps:
      - checkout
      - run: |
          node -v
          npm -v
      - run: |
          npm install
          npm list
      - run:
          name: inspect NPM debug logs
          command: tail -n 100 /root/project/npm-debug.log
          when: on_fail
      - run:
          name: list installed packages
          command: npm list --depth=0
          when: always

workflows:
  main:
    jobs:
      - node-test
